import fs from 'fs';
import path from 'path';
import axios from 'axios';
import Papa from 'papaparse';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const CSV_URL = 'https://docs.google.com/spreadsheets/d/142d91qR1faUzUc1tE17PAMa6OXvAzZd20b5IZpwjD68/export?format=csv&gid=0';
const JSON_FILE = path.join(__dirname, '../src/data/reviews.json');

async function main() {
  console.log('Downloading CSV from Google Sheets...');
  try {
    const csvResponse = await axios.get(CSV_URL);
    const parsed = Papa.parse(csvResponse.data, { header: true, skipEmptyLines: true });
    const rows = parsed.data;
    
    // Read existing JSON
    const reviews = JSON.parse(fs.readFileSync(JSON_FILE, 'utf-8'));

    let currentLink = '';
    let jsonIdx = 0;

    for (let i = 0; i < rows.length; i++) {
      const row = rows[i];
      const movieTitle = row['Movie'];
      if (!movieTitle) continue;

      if (row['Links']) {
        currentLink = row['Links'];
      }

      // The json was generated by skipping empty titles, so we iterate identically
      if (jsonIdx < reviews.length) {
        reviews[jsonIdx].link = currentLink;
        jsonIdx++;
      }
    }

    fs.writeFileSync(JSON_FILE, JSON.stringify(reviews, null, 2));
    console.log(`Successfully updated links for ${reviews.length} records.`);
  } catch (error) {
    console.error('Error:', error.message);
  }
}

main();
